language: ruby
rvm:
  - 2.4.1
after_success:
 # - bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
